### PR TITLE
Add CPU frequency configuration to menu

### PR DESCRIPTION
**Pull request by UzixLS**
F4-F8 keys now work as momentary switches, not as latch switches

### CODE REVIEW

**Comment by gyurco** [comment]
Thanks for the patches! I have a question about this one: you have to keep holding down the F-key for turbo? Why not just leave the switch functionality by F-Keys as now, and switch turbo mode from the OSD when: reset OR the OSD setting change (e.g. old_st_cpu_freq != st_cpu_freq)

**Comment by UzixLS** [comment]
There is one technical and one subjective reason for that:
1 - To use F-keys as latch switches it's required to send current CPU frequency setting back to ARM. Otherwise configuration menu doesn't reflect the actual state, which would be confusing. I don't know if there any way to send back configuration options from FPGA to ARM.
2 - Momentary switches would be convenient for temporary quick-accessible speed-up. And for permanent speed-up there is configuration menu entry (which also may be saved to cfg file). I don't see the point of duplicating the permanent configuration on the F-keys.

This PR reflects only my subjective opinion about UX, so feel free to reject.

**Comment by gyurco** [comment]
It's true that no feedback from the core to the menu is implemented yet. I'll think about it in the future.
My problem is that keeping the F-key pressed is not very friendly, thus my proposal is to switch the speed temporary until a change in the OSD or a reset is done. This is already the case when you load a Z80 file - it'll temporary override the machine memory configuration according to the .Z80 header.

**Comment by UzixLS** [comment]
I propose to drop this PR as I have no interest to implement this logic.

**Comment by gyurco** [comment]
No problem, thanks for interested anyway.

**Pull request closed without merging**
